/**
 * {@link https://icon-sets.iconify.design/ic/}
 */

export { default as PlaceholderIcon } from './placeholder.svg?react'
export { default as Back } from '@material-icons/svg/svg/arrow_back_ios_new/round.svg?react'
export { default as Battery } from '@material-icons/svg/svg/battery_50/round.svg?react'
export { default as Check } from '@material-icons/svg/svg/check/round.svg?react'
export { default as Circle } from '@material-icons/svg/svg/circle/outline.svg?react'
export { default as Close } from '@material-icons/svg/svg/close/outline.svg?react'
export { default as Copy } from '@material-icons/svg/svg/content_copy/round.svg?react'
export { default as Download } from '@material-icons/svg/svg/download/round.svg?react'
export { default as FilePresent } from '@material-icons/svg/svg/file_present/round.svg?react'
export { default as ArrowDown } from '@material-icons/svg/svg/keyboard_arrow_down/round.svg?react'
export { default as Link } from '@material-icons/svg/svg/link/round.svg?react'
export { default as Pause } from '@material-icons/svg/svg/pause/baseline.svg?react'
export { default as Play } from '@material-icons/svg/svg/play_arrow/baseline.svg?react'
export { default as Replay } from '@material-icons/svg/svg/replay/round.svg?react'
export { default as AlertOctagon } from '@material-icons/svg/svg/report/round.svg?react'
export { default as AlertTriangle } from '@material-icons/svg/svg/report_problem/round.svg?react'
export { default as Search } from '@material-icons/svg/svg/search/round.svg?react'
export { default as Settings } from '@material-icons/svg/svg/settings/round.svg?react'
export { default as Cellular } from '@material-icons/svg/svg/signal_cellular_4_bar/round.svg?react'
export { default as Wifi } from '@material-icons/svg/svg/signal_wifi_4_bar/round.svg?react'
export { default as Square } from '@material-icons/svg/svg/square/round.svg?react'
export { default as Upload } from '@material-icons/svg/svg/upload_file/round.svg?react'
